1.Write a Python program to convert a list of numeric value into a one-dimensional


In [3]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:30:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 02:30:30.
@Title :Python program to convert list to numpy array

'''


import numpy as np
def main():
    lis = [12.23, 13.32, 100, 36.32]
    array = np.array(lis)
    print(array)


if __name__ == '__main__':
    main()

'\n@Author: v sanjay kumar\n@Date: 2024-07-25 11:30:30\n@Last Modified by: v sanjay kumar\n@Last Modified time: 2024-07-25 11:30:30.\n@Title :Python program to \n\n'

2. Create a 3x3 matrix with values ranging from 2 to 10.

In [2]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :Python program to take range 2 to 10 and add the 3*3 matrix 

'''


import numpy as np
def main():
    a=np.arange(2,11).reshape((3,3))
    print(a)


if __name__ == '__main__':
    main()


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [1]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :Python program create numpy array with zeros

'''

import numpy as np
def main():
    array =np.zeros(10)
    array[5]=11
    print(array)

if __name__ == '__main__':
    main()

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [ ]:
import numpy as np
import random
import sys


4. Write a Python program to reverse an array (first element becomes last).


In [9]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :Python program to reverse the  numpy array

'''

def main():
    
    array =np.arange(12,38)
    
    print('Before Reversing the array',array)
    rev =np.flip(array)
    print('after reversing the array',rev)

if __name__ == '__main__':
    main()

Before Reversing the array [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
after reversing the array [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [19]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :Python program to create a 2d array with 1 on the border and 0 inside.

'''

def main():
    size_matrix =int(input("Enter size of the matrix"))
    array = np.ones((size_matrix,size_matrix))
    array[1:-1,1:-1]=0
    print(array)

if __name__ == '__main__':
    main()

[[1. 1. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [34]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :Python program to o add a border (filled with 0's) around an existing array.
'''
def change(arr):
    ''''
    descripton
      take the array fillied with 0's'

    Parameters:
    - arr(numpy array):numpy array.
    
    Returns:
    - filled with 0 arround(list).-return the new numpy.'''
    for row in range(arr.shape[0]):
        for col in range(arr.shape[0]):
            if row == 0 or row ==arr.shape[0]-1 or col ==0 or col ==arr.shape[0]-1:
                arr[row,col]=0
    
    return arr


        
    
def main():
    size_matrix =int(input("Enter size of the matrix"))
    array =np.ones(size_matrix*size_matrix)
    array=array.reshape(size_matrix,size_matrix)
    print('initial array is',array)
    arr = np.ones((size_matrix+2)*(size_matrix+2))
    arr=arr.reshape(size_matrix+2,size_matrix+2)
    print(change(arr))
if __name__ == '__main__':
    main()

initial array is [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern.
Checkerboard pattern:

In [33]:
'''

@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :Python program to o add a border (filled with 0's) around an existing array.
'''



def main():
    try:
        size_matrix =int(input("Enter size of the matrix"))
        array =np.ones(size_matrix*size_matrix)
        array=array.reshape(size_matrix,size_matrix)
        print('initial array is',array)
        for row in range(array.shape[0]):
            for col in range(array.shape[1]):
                if (row % 2==0 and col % 2==0):
                    array[row,col]=0
                if(row % 2 !=0 and col %2 ==0):
                    array[row,col] =0
        print("final array is ",array)
    except Exception as e:
        print("invalid input enter only numeric value",e)


if __name__ == '__main__':
    main()




invalid input enter only numeric value invalid literal for int() with base 10: 'd'


8.Python program to convert a list and tuple into arrays.List to array

In [36]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :Python program to convert a list and tuple into arrays.List to array
'''


def main():
    lis =list(map(int,input()))
    tup =tuple(map(int,input()))
    array1=np.array(lis)
    array2 =np.array(tup)
    print(f"list is converted in numpy{array1},tuple is convered numpy{array2}")

if __name__ == "__main__":
    main()

list is converted in numpy[1 2 3 4],tuple is convered in[1 2 3 4]


9.Write a Python program to append values to the end of an array.

In [45]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :Python program to convert a list and tuple into arrays.List to array
'''


def main():
    
    array =np.array([2,4,5,6,5])
    
    array=np.append(array,7)
    
    print(array)

if __name__ == "__main__":
    main()

[2 4 5 6 5 7]


10. Write a Python program to find the real and imaginary parts of an array of complex
numbers.

In [48]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :program to  find the real and imaginary parts of an array of complex.
'''




def main():
    array =np.array([1+9j,2+2j,5+6j,4+0j])

    for i in range(len(array)):
        print(f"imaginary part of {array[i]} is",array[i].imag)
    
        print(f'real part part of {array[i]} is',array[i].real)



if __name__ == '__main__':
    main()

imaginary part of (1+9j)  9.0
real part part of (1+9j) 1.0
imaginary part of (2+2j)  2.0
real part part of (2+2j) 2.0
imaginary part of (5+6j)  6.0
real part part of (5+6j) 5.0
imaginary part of (4+0j)  0.0
real part part of (4+0j) 4.0


11. Write a Python program to find the number of elements of an array, length of one
array element in bytes and total bytes consumed by the elements.

In [51]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :program to  find number of elements and size of element and total bytes
'''

def main():
    array =np.array([1,5,6,4,3,3,67,5,4,4],dtype=np.int16)
    print('number of elements in array',len(array))
    print('length of one element in array',array[0].itemsize)
    print("total bytes consumed by array",len(array)*array.itemsize)


if __name__ == '__main__':
    main()







number of elements in array 10
length of one element in array 2
total bytes consumed by array 20


12.Write a Python program to find common values between two arrays.

In [56]:
'''
@Author: v sanjay kumar
@Date: 2024-08-06 02:40:30
@Last Modified by: v sanjay kumar
@Last Modified time: 2024-08-06 03:30:30.
@Title :program to  find common values between two arrays.

'''
def main():
    
    comman =np.array([])
    array =np.array([13,56,3,2,1,3,4,2,1,6])
    array2 =np.array([3,4,5,6,7,8,6,54])
    for i in array:
        for j in array2:
            if i == j:
                comman =np.append(comman,i)

    print(comman) 


if __name__ == "__main__":
    main()

[3. 3. 4. 6. 6.]


3. Write a Python program to find the set difference of two arrays. The set difference
will return the sorted, unique values in array1 that are not in array2.

In [61]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-06 02:40:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-06 03:30:30.
    @Title :program to  find difference between two arrays.

'''


def main():
    array =np.array([13,56,36,1,3,4,2,1,,96])
    array2 =np.array([3,4,5,6,7,8,6,54])
    dif =np.array([])

    for i in array:
       if(i not in array2):
           dif =np.append(dif,i)

    print(dif)


if __name__ =='__main__':
    main()


[13. 56.  2.  1.  2.  1.]


14.Python program to find the set exclusive-or of two arrays. 

In [65]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-06 02:40:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-06 03:30:30.
    @Title :program to  find symmetric difference between two arrays.

'''

def main():
    array =np.array([13,56,3,2,1,3,4,2,1,6])
    array2 =np.array([3,4,5,6,7,8,6,54])
    

    print("The Symmetric  difference of array1,array2:",np.setxor1d(array,array2))


if __name__ =='__main__':
    main()

The Symmetric  difference of array1,array2 [ 1  2  5  7  8 13 54 56]


15.Python program compare two arrays using numpy.

In [67]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-06 02:40:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-06 03:30:30.
    @Title :Python program compare two arrays using numpy.
'''
 

def main():
    f_array = np.array([1,3,4,5,6,4])
    s_array = np.array([1,2,3,4,5,6])

    print(f_array == s_array)
    print(f_array != s_array)
    print(f_array < s_array)
    print(f_array > s_array)
    print(f_array <= s_array)
    print(f_array >= s_array)

if __name__ == '__main__':
    main()

[ True False False False False False]
[False  True  True  True  True  True]
[False False False False False  True]
[False  True  True  True  True False]
[ True False False False False  True]
[ True  True  True  True  True False]


16.Write a Python program to save a NumPy array to a text file.

In [104]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-06 02:40:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-06 03:30:30.
    @Title :Python program compare two arrays using numpy.
'''
def main():
    
    List = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
    Array = np.array(List)
    
    print('Array:\n', Array)

    np.savetxt("file1.txt", Array)
    
    content = np.loadtxt('file1.txt')
    print("\nContent in file1.txt:\n", content)


if __name__ == "__main__":
    main()

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Content in file1.txt:
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


17. Write a Python program to create a contiguous flattened array.

In [76]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-06 02:40:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-06 03:30:30.
    @Title :Python program  to create a contiguous flattened array.

'''

def main():
    array = np.random.randint(4, 19, size=(3, 3))
    print('Initial array:')
    print(array)
    
    flattened_array = array.flatten()
    print('Flattened array:')
    print(flattened_array)


if __name__ == '__main__':
    main()


Initial array:
[[ 7 16  6]
 [12 10 10]
 [ 4 10 10]]
Flattened array:
[ 7 16  6 12 10 10  4 10 10]


18.Write a Python program to change the data type of an array

In [90]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-06 02:40:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-06 03:30:30.
    @Title :Python program  to change the data type
'''

def main():
    array =np.array([1,3,4,5,6,33,4])
    print(array)
    print(array.dtype)

    new =array.astype(np.float64)
    print(new)
    print(new.dtype)
    

if __name__ == '__main__':
    main()

[ 1  3  4  5  6 33  4]
int64
[ 1.  3.  4.  5.  6. 33.  4.]
float64


19.Write a Python program to create a 3-D array with ones on a diagonal and zeros


In [93]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-06 02:40:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-06 03:30:30.
    @Title :Python program  to change the data type
'''

def main():
     
    array =np.zeros((3,3))
    print('initial list is',array)

    for row in range(len(array[0])):
        for col in range(len(array[1])):
            if row == col:
                array[row, col] =1
            
    print('final list is',array)


if __name__ == '__main__':
    main()



initial list is [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
final list is [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


20. Write a Python program to create an array which looks like below array.

In [99]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-06 02:40:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-06 03:30:30.
    @Title :Python program  to change the data type
'''

def main():
    size_array =int(input("Enter a size" ))
    array =np.zeros((size_array,size_array))
    for i in range(size_array):
        array[i,:i+1]=1

    print(array)             




if __name__ == '__main__':
    main()


[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


21. Write a Python program to concatenate two 2-dimensional arrays

In [103]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-06 02:40:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-06 03:30:30.
    @Title :program to concatenate two 2-dimensional arrays.
    '''
def main():
    array = np.array([[0, 1, 3], [5, 7, 9]])
    array1 =np.array([[0, 2, 4], [6, 8, 10]])

    new =np.concatenate((array,array1) ,axis=1)
    print(new)


if __name__ == '__main__':
    main()


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


22. Write a Python program to make an array immutable (read-only)

In [1]:
'''@Author: v sanjay kumar
    @Date: 2024-08-08 010:00:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-08 10:00:30.
    @Title :program to to make an array immutable.
'''
def main():
    
    import numpy as np

    arr = np.array([1, 2, 3, 4, 5])
    arr.flags.writeable = False

    
    try:
        arr[0] = 10
    except ValueError as e:
        print(e)

    
if __name__ =='__main__':
    main()

assignment destination is read-only


In [4]:
import numpy as np

23.Write a Python program to create an array of (3, 4) shape, multiply every element
value by 3 and display the new array.


In [38]:
'''@Author: v sanjay kumar
    @Date: 2024-08-08 010:20:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-08 10:20:30.
    @Title :program to to multiply array with 3.
'''
def main():
    array = np.arange(0,12)
    array=array.reshape(3,4)
    print('intial array\n',array)

    print('final array\n',array*3)


if __name__ == '__main__':
    main()

intial array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
final array
 [[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


24.Write a Python program to convert a NumPy array into Python list structure

In [53]:
'''@Author: v sanjay kumar
    @Date: 2024-08-08 010:20:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-08 10:20:30.
    @Title :program to to convert a NumPy array into Python list structure.
'''

def main():
    
    array = np.array([] ,dtype=int)
    size=int(input())

    for _ in range(size):
        n=int(input('Enter a number'))
        array =np.append(array,n)
    print('the numpy array is',array)
    lis=array.tolist()
    print('The python list structure is',lis)


if __name__ == '__main__':
    main()
    

the numpy array is [1 2 1]
The python list structure is [1, 2, 1]


25.Write a Python program to convert a NumPy array into Python list structure

In [56]:
'''@Author: v sanjay kumar
    @Date: 2024-08-08 010:20:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-08 10:20:30.
    @Title :program to to convert a NumPy array into Python list structure.
'''

def main():
    array = np.random.random(6)
    print('The original array',array)
    new =array.tolist()

    print('The list of the array is',new)

    print('The final after precicion',[round(ele,3) for ele in new])




if __name__ == '__main__':
    main()


The original array [0.46040632 0.09877228 0.01637387 0.34175129 0.9622039  0.5308586 ]
The list of the array is [0.4604063186912185, 0.09877227821869805, 0.01637387419483205, 0.3417512899047874, 0.9622039024985275, 0.5308585962104735]
The final after precicion [0.46, 0.099, 0.016, 0.342, 0.962, 0.531]


26.Write a Python program to suppresses the use of scientific notation for small
numbers in numpy array.


In [62]:
'''@Author: v sanjay kumar
    @Date: 2024-08-08 010:20:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-08 10:20:30.
    @Title :program  suppresses the use of scientific notation for small numbers in numpy array.

'''

def main():
    
    np.set_printoptions(suppress=True,precision=2) 

    array = np.array([ 1.0000000e-10, 1.60000000e+00 ,1.20000000e+03 ,2.35000000e-01])

    # array=array.round(100)

    print(array)


if __name__ == '__main__':
    main()
    


[   0.      1.6  1200.      0.23]


27.Write a Python program to how to add an extra column to an numpy array.


In [64]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-08 010:20:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-08 10:20:30.
    @Title :program to how to add an extra column to an numpy array.

'''

def main():
    x = np.array([[10, 20, 30], [40, 50, 60]])
    print('First array\n',x)
    y = np.array([[100], [200]])
    print('Second array is \n',y)
    new =np.append(x, y,axis=1)
    
    print('The modified array is\n',new)

if __name__ == '__main__':
    main()

First array
 [[10 20 30]
 [40 50 60]]
Second array is 
 [[100]
 [200]]
The modified array is
 [[ 10  20  30 100]
 [ 40  50  60 200]]


28. Write a Python program to remove specific elements in a numpy array.


In [67]:
'''
    @Author: v sanjay kumar
    @Date: 2024-08-08 010:20:30
    @Last Modified by: v sanjay kumar
    @Last Modified time: 2024-08-08 10:20:30.
    @Title :program to  to remove specific elements in a numpy array.

'''

def main():
    array =np.array([1,2,9,20,3,4,5])
    
    print("remaining elements after deleting 1st fourth and fifith  elements",np.delete(array, [0, 3,4]))
    

if __name__ == '__main__':
    main()

remaining elements after deleting 1st fourth and fifith  elements [2 9 4 5]
